### ISSUE TITLE
Line.replace is not a function

### ISSUE THREAD

**Issue by Trainmaster2** [QSmally/QCPU-Assembler#2]
When I first tried running this, it told me there was an extra parenthesis. I removed the extra parenthesis, but then it told me that `Line.replace` wasn't a function.

```
QCPU-Assembler-master/Main.js:22
    .map(Line => Line.replace("$", "")))
                                       ^

SyntaxError: Unexpected token ')'
```
```
QCPU-Assembler-master/Main.js:22
    .map(Line => Line.replace("$", ""))
                      ^

TypeError: Line.replace is not a function
```

To potentially save you a step, here's what Program looks like before it hits that line on the default program.
`[ [ 'LIM', '$0' ], [ '175' ] ]`

**Comment by QSmally** [comment]
Pushed a fix I did a long time ago, thanks
